### ISSUE TITLE
All actions should be able to have their own keyboard shortcut

### ISSUE THREAD

**Issue by patkujawa-wf** [georgelesica-wf/bendium#12]
Somewhere along the way, we lost our way ;)
![image](https://cloud.githubusercontent.com/assets/6391742/26597720/2313c910-4530-11e7-9a33-972c7e617c1f.png)

@georgelesica-wf @charliekump-wf

**Comment by charliekump-wf** [comment]
Sounds like a personal problem... @patkujawa-wf ;)

**Comment by patkujawa-wf** [comment]
Hah! Well, it is! :)

**Comment by georgelesica-wf** [comment]
I believe this has been resolved, could you confirm and then close @patkujawa-wf ?

![image](https://user-images.githubusercontent.com/7902990/38001611-fcebc7d0-31ea-11e8-8d81-2903383f883a.png)

**Comment by patkujawa-wf** [comment]
Yep
