### ISSUE TITLE
Dropdown cutoff occasionally

### ISSUE THREAD

**Issue by charliekump-wf** [georgelesica-wf/bendium#16]
Occassionally the dropdown gets cutover. Retry or switching tabs seems to resolve.

https://s3.amazonaws.com/uploads.hipchat.com/12595/396878/bXhhFzkFOyDaDkp/Screen%20Shot%202017-08-02%20at%205.12.32%20PM.png

**Comment by georgelesica-wf** [comment]
This has been resolved.
