### ISSUE TITLE
Should allow setting a hipchat room in which to talk to Bender

### ISSUE THREAD

**Issue by patkujawa-wf** [georgelesica-wf/bendium#2]
Easiest to just supply the room's API id. One challenge is that if Bender isn't already in the room (which can happen after he's updated and re-deployed), then the first message just brings him into the room but he doesn't act on it. However, if he's already in the room and we send the message twice, he'll act on it twice.

**Comment by travissanderson-wf** [comment]
I don't think the maintainer of this repo really cares about his userbase

**Comment by georgelesica-wf** [comment]
What's the value here? Doesn't it make sense to just have a direct conversation with Bender?

**Comment by patkujawa-wf** [comment]
I can't even remember. I don't see a lot of need/value right now either :)
